version: "3.3"
services:
  wp:
    build:
      context: .
      args:
        - IMAGE=wordpress
        - IDE_NAME=PhpStorm 2021.2.3
    ports:
      - 9999:9999
      - 8000:80
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    